Avoid Coveralls upload failure because build was closed
Error: Unprocessable Entity
Can't add a job to a build that is already closed.
See docs.coveralls.io/parallel-builds